package com.inm.ap.mode.hibernate;
// Generated Jan 25, 2018 9:36:12 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * AccountRevenueInformation generated by hbm2java
 */
public class AccountRevenueInformation  implements java.io.Serializable {


     private int accountRevenueid;
     private ClientMaster clientMaster;
     private BigDecimal currentyearrevenuetarget;
     private BigDecimal prioryearactualrevenue;
     private BigDecimal percentagegrowthrevenue;
     private BigDecimal currentyearfeeincometarget;
     private BigDecimal prioryearactualfeeincome;
     private BigDecimal percentagegrowthfeeincome;
     private BigDecimal currentshareofwallet;
     private BigDecimal targetshareofwallet;
     private BigDecimal totalvalueofidopportunities;

    public AccountRevenueInformation() {
    }

	
    public AccountRevenueInformation(int accountRevenueid, ClientMaster clientMaster) {
        this.accountRevenueid = accountRevenueid;
        this.clientMaster = clientMaster;
    }
    public AccountRevenueInformation(int accountRevenueid, ClientMaster clientMaster, BigDecimal currentyearrevenuetarget, BigDecimal prioryearactualrevenue, BigDecimal percentagegrowthrevenue, BigDecimal currentyearfeeincometarget, BigDecimal prioryearactualfeeincome, BigDecimal percentagegrowthfeeincome, BigDecimal currentshareofwallet, BigDecimal targetshareofwallet, BigDecimal totalvalueofidopportunities) {
       this.accountRevenueid = accountRevenueid;
       this.clientMaster = clientMaster;
       this.currentyearrevenuetarget = currentyearrevenuetarget;
       this.prioryearactualrevenue = prioryearactualrevenue;
       this.percentagegrowthrevenue = percentagegrowthrevenue;
       this.currentyearfeeincometarget = currentyearfeeincometarget;
       this.prioryearactualfeeincome = prioryearactualfeeincome;
       this.percentagegrowthfeeincome = percentagegrowthfeeincome;
       this.currentshareofwallet = currentshareofwallet;
       this.targetshareofwallet = targetshareofwallet;
       this.totalvalueofidopportunities = totalvalueofidopportunities;
    }
   
    public int getAccountRevenueid() {
        return this.accountRevenueid;
    }
    
    public void setAccountRevenueid(int accountRevenueid) {
        this.accountRevenueid = accountRevenueid;
    }
    public ClientMaster getClientMaster() {
        return this.clientMaster;
    }
    
    public void setClientMaster(ClientMaster clientMaster) {
        this.clientMaster = clientMaster;
    }
    public BigDecimal getCurrentyearrevenuetarget() {
        return this.currentyearrevenuetarget;
    }
    
    public void setCurrentyearrevenuetarget(BigDecimal currentyearrevenuetarget) {
        this.currentyearrevenuetarget = currentyearrevenuetarget;
    }
    public BigDecimal getPrioryearactualrevenue() {
        return this.prioryearactualrevenue;
    }
    
    public void setPrioryearactualrevenue(BigDecimal prioryearactualrevenue) {
        this.prioryearactualrevenue = prioryearactualrevenue;
    }
    public BigDecimal getPercentagegrowthrevenue() {
        return this.percentagegrowthrevenue;
    }
    
    public void setPercentagegrowthrevenue(BigDecimal percentagegrowthrevenue) {
        this.percentagegrowthrevenue = percentagegrowthrevenue;
    }
    public BigDecimal getCurrentyearfeeincometarget() {
        return this.currentyearfeeincometarget;
    }
    
    public void setCurrentyearfeeincometarget(BigDecimal currentyearfeeincometarget) {
        this.currentyearfeeincometarget = currentyearfeeincometarget;
    }
    public BigDecimal getPrioryearactualfeeincome() {
        return this.prioryearactualfeeincome;
    }
    
    public void setPrioryearactualfeeincome(BigDecimal prioryearactualfeeincome) {
        this.prioryearactualfeeincome = prioryearactualfeeincome;
    }
    public BigDecimal getPercentagegrowthfeeincome() {
        return this.percentagegrowthfeeincome;
    }
    
    public void setPercentagegrowthfeeincome(BigDecimal percentagegrowthfeeincome) {
        this.percentagegrowthfeeincome = percentagegrowthfeeincome;
    }
    public BigDecimal getCurrentshareofwallet() {
        return this.currentshareofwallet;
    }
    
    public void setCurrentshareofwallet(BigDecimal currentshareofwallet) {
        this.currentshareofwallet = currentshareofwallet;
    }
    public BigDecimal getTargetshareofwallet() {
        return this.targetshareofwallet;
    }
    
    public void setTargetshareofwallet(BigDecimal targetshareofwallet) {
        this.targetshareofwallet = targetshareofwallet;
    }
    public BigDecimal getTotalvalueofidopportunities() {
        return this.totalvalueofidopportunities;
    }
    
    public void setTotalvalueofidopportunities(BigDecimal totalvalueofidopportunities) {
        this.totalvalueofidopportunities = totalvalueofidopportunities;
    }




}


