package com.inm.ap.mode.hibernate;
// Generated Feb 19, 2018 4:06:43 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * ClientFinancial generated by hbm2java
 */
public class ClientFinancial  implements java.io.Serializable {


     private int clientFinancialid;
     private ClientMaster clientMaster;
     private BigDecimal turnover;
     private BigDecimal operatingprofit;
     private BigDecimal totaldebt;
     private BigDecimal totaldeposits;
     private BigDecimal gearingratio;
     private BigDecimal cashflowcycle;
     private BigDecimal totalassets;
     private BigDecimal totalcapital;

    public ClientFinancial() {
    }

	
    public ClientFinancial(int clientFinancialid, ClientMaster clientMaster, BigDecimal totaldebt) {
        this.clientFinancialid = clientFinancialid;
        this.clientMaster = clientMaster;
        this.totaldebt = totaldebt;
    }
    public ClientFinancial(int clientFinancialid, ClientMaster clientMaster, BigDecimal turnover, BigDecimal operatingprofit, BigDecimal totaldebt, BigDecimal totaldeposits, BigDecimal gearingratio, BigDecimal cashflowcycle, BigDecimal totalassets, BigDecimal totalcapital) {
       this.clientFinancialid = clientFinancialid;
       this.clientMaster = clientMaster;
       this.turnover = turnover;
       this.operatingprofit = operatingprofit;
       this.totaldebt = totaldebt;
       this.totaldeposits = totaldeposits;
       this.gearingratio = gearingratio;
       this.cashflowcycle = cashflowcycle;
       this.totalassets = totalassets;
       this.totalcapital = totalcapital;
    }
   
    public int getClientFinancialid() {
        return this.clientFinancialid;
    }
    
    public void setClientFinancialid(int clientFinancialid) {
        this.clientFinancialid = clientFinancialid;
    }
    public ClientMaster getClientMaster() {
        return this.clientMaster;
    }
    
    public void setClientMaster(ClientMaster clientMaster) {
        this.clientMaster = clientMaster;
    }
    public BigDecimal getTurnover() {
        return this.turnover;
    }
    
    public void setTurnover(BigDecimal turnover) {
        this.turnover = turnover;
    }
    public BigDecimal getOperatingprofit() {
        return this.operatingprofit;
    }
    
    public void setOperatingprofit(BigDecimal operatingprofit) {
        this.operatingprofit = operatingprofit;
    }
    public BigDecimal getTotaldebt() {
        return this.totaldebt;
    }
    
    public void setTotaldebt(BigDecimal totaldebt) {
        this.totaldebt = totaldebt;
    }
    public BigDecimal getTotaldeposits() {
        return this.totaldeposits;
    }
    
    public void setTotaldeposits(BigDecimal totaldeposits) {
        this.totaldeposits = totaldeposits;
    }
    public BigDecimal getGearingratio() {
        return this.gearingratio;
    }
    
    public void setGearingratio(BigDecimal gearingratio) {
        this.gearingratio = gearingratio;
    }
    public BigDecimal getCashflowcycle() {
        return this.cashflowcycle;
    }
    
    public void setCashflowcycle(BigDecimal cashflowcycle) {
        this.cashflowcycle = cashflowcycle;
    }
    public BigDecimal getTotalassets() {
        return this.totalassets;
    }
    
    public void setTotalassets(BigDecimal totalassets) {
        this.totalassets = totalassets;
    }
    public BigDecimal getTotalcapital() {
        return this.totalcapital;
    }
    
    public void setTotalcapital(BigDecimal totalcapital) {
        this.totalcapital = totalcapital;
    }




}


