package com.inm.ap.mode.hibernate;
// Generated Feb 19, 2018 4:06:43 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ClientMaster generated by hbm2java
 */
public class ClientMaster  implements java.io.Serializable {


     private String clientid;
     private RmCodelist rmCodelistByRmCode;
     private RmCodelist rmCodelistByAlternativeRmCode;
     private Lookupmaster lookupmaster;
     private String clientname;
     private Date currentDate;
     private String tradeserviceprovider;
     private String cashmanagementpartner;
     private String ECommercepartner;
     private String creditmanager;
     private String treasurypartner;
     private String internetbankingpartner;
     private String assetfinancepartner;
     private String cardspartner;
     private String bancassurancepartner;
     private Set overallclientwalletsizes = new HashSet(0);
     private Set walletResizes = new HashSet(0);
     private Set qualitativeinformations = new HashSet(0);
     private Set signOffs = new HashSet(0);
     private Set companyMasters = new HashSet(0);
     private Set currentandfutureopportunitieses = new HashSet(0);
     private Set clientcoverageprofiles = new HashSet(0);
     private Set dealinprogresses = new HashSet(0);
     private Set clientFinancials = new HashSet(0);
     private Set keysuppliermasters = new HashSet(0);
     private Set accountRevenueInformations = new HashSet(0);
     private Set competitions = new HashSet(0);
     private Set keydistributormasters = new HashSet(0);
     private Set clientEmployees = new HashSet(0);
     private Set creditInformations = new HashSet(0);
     private Set salesactionplans = new HashSet(0);

    public ClientMaster() {
    }

	
    public ClientMaster(String clientid, RmCodelist rmCodelistByRmCode, RmCodelist rmCodelistByAlternativeRmCode) {
        this.clientid = clientid;
        this.rmCodelistByRmCode = rmCodelistByRmCode;
        this.rmCodelistByAlternativeRmCode = rmCodelistByAlternativeRmCode;
    }
    public ClientMaster(String clientid, RmCodelist rmCodelistByRmCode, RmCodelist rmCodelistByAlternativeRmCode, Lookupmaster lookupmaster, String clientname, Date currentDate, String tradeserviceprovider, String cashmanagementpartner, String ECommercepartner, String creditmanager, String treasurypartner, String internetbankingpartner, String assetfinancepartner, String cardspartner, String bancassurancepartner, Set overallclientwalletsizes, Set walletResizes, Set qualitativeinformations, Set signOffs, Set companyMasters, Set currentandfutureopportunitieses, Set clientcoverageprofiles, Set dealinprogresses, Set clientFinancials, Set keysuppliermasters, Set accountRevenueInformations, Set competitions, Set keydistributormasters, Set clientEmployees, Set creditInformations, Set salesactionplans) {
       this.clientid = clientid;
       this.rmCodelistByRmCode = rmCodelistByRmCode;
       this.rmCodelistByAlternativeRmCode = rmCodelistByAlternativeRmCode;
       this.lookupmaster = lookupmaster;
       this.clientname = clientname;
       this.currentDate = currentDate;
       this.tradeserviceprovider = tradeserviceprovider;
       this.cashmanagementpartner = cashmanagementpartner;
       this.ECommercepartner = ECommercepartner;
       this.creditmanager = creditmanager;
       this.treasurypartner = treasurypartner;
       this.internetbankingpartner = internetbankingpartner;
       this.assetfinancepartner = assetfinancepartner;
       this.cardspartner = cardspartner;
       this.bancassurancepartner = bancassurancepartner;
       this.overallclientwalletsizes = overallclientwalletsizes;
       this.walletResizes = walletResizes;
       this.qualitativeinformations = qualitativeinformations;
       this.signOffs = signOffs;
       this.companyMasters = companyMasters;
       this.currentandfutureopportunitieses = currentandfutureopportunitieses;
       this.clientcoverageprofiles = clientcoverageprofiles;
       this.dealinprogresses = dealinprogresses;
       this.clientFinancials = clientFinancials;
       this.keysuppliermasters = keysuppliermasters;
       this.accountRevenueInformations = accountRevenueInformations;
       this.competitions = competitions;
       this.keydistributormasters = keydistributormasters;
       this.clientEmployees = clientEmployees;
       this.creditInformations = creditInformations;
       this.salesactionplans = salesactionplans;
    }
   
    public String getClientid() {
        return this.clientid;
    }
    
    public void setClientid(String clientid) {
        this.clientid = clientid;
    }
    public RmCodelist getRmCodelistByRmCode() {
        return this.rmCodelistByRmCode;
    }
    
    public void setRmCodelistByRmCode(RmCodelist rmCodelistByRmCode) {
        this.rmCodelistByRmCode = rmCodelistByRmCode;
    }
    public RmCodelist getRmCodelistByAlternativeRmCode() {
        return this.rmCodelistByAlternativeRmCode;
    }
    
    public void setRmCodelistByAlternativeRmCode(RmCodelist rmCodelistByAlternativeRmCode) {
        this.rmCodelistByAlternativeRmCode = rmCodelistByAlternativeRmCode;
    }
    public Lookupmaster getLookupmaster() {
        return this.lookupmaster;
    }
    
    public void setLookupmaster(Lookupmaster lookupmaster) {
        this.lookupmaster = lookupmaster;
    }
    public String getClientname() {
        return this.clientname;
    }
    
    public void setClientname(String clientname) {
        this.clientname = clientname;
    }
    public Date getCurrentDate() {
        return this.currentDate;
    }
    
    public void setCurrentDate(Date currentDate) {
        this.currentDate = currentDate;
    }
    public String getTradeserviceprovider() {
        return this.tradeserviceprovider;
    }
    
    public void setTradeserviceprovider(String tradeserviceprovider) {
        this.tradeserviceprovider = tradeserviceprovider;
    }
    public String getCashmanagementpartner() {
        return this.cashmanagementpartner;
    }
    
    public void setCashmanagementpartner(String cashmanagementpartner) {
        this.cashmanagementpartner = cashmanagementpartner;
    }
    public String getECommercepartner() {
        return this.ECommercepartner;
    }
    
    public void setECommercepartner(String ECommercepartner) {
        this.ECommercepartner = ECommercepartner;
    }
    public String getCreditmanager() {
        return this.creditmanager;
    }
    
    public void setCreditmanager(String creditmanager) {
        this.creditmanager = creditmanager;
    }
    public String getTreasurypartner() {
        return this.treasurypartner;
    }
    
    public void setTreasurypartner(String treasurypartner) {
        this.treasurypartner = treasurypartner;
    }
    public String getInternetbankingpartner() {
        return this.internetbankingpartner;
    }
    
    public void setInternetbankingpartner(String internetbankingpartner) {
        this.internetbankingpartner = internetbankingpartner;
    }
    public String getAssetfinancepartner() {
        return this.assetfinancepartner;
    }
    
    public void setAssetfinancepartner(String assetfinancepartner) {
        this.assetfinancepartner = assetfinancepartner;
    }
    public String getCardspartner() {
        return this.cardspartner;
    }
    
    public void setCardspartner(String cardspartner) {
        this.cardspartner = cardspartner;
    }
    public String getBancassurancepartner() {
        return this.bancassurancepartner;
    }
    
    public void setBancassurancepartner(String bancassurancepartner) {
        this.bancassurancepartner = bancassurancepartner;
    }
    public Set getOverallclientwalletsizes() {
        return this.overallclientwalletsizes;
    }
    
    public void setOverallclientwalletsizes(Set overallclientwalletsizes) {
        this.overallclientwalletsizes = overallclientwalletsizes;
    }
    public Set getWalletResizes() {
        return this.walletResizes;
    }
    
    public void setWalletResizes(Set walletResizes) {
        this.walletResizes = walletResizes;
    }
    public Set getQualitativeinformations() {
        return this.qualitativeinformations;
    }
    
    public void setQualitativeinformations(Set qualitativeinformations) {
        this.qualitativeinformations = qualitativeinformations;
    }
    public Set getSignOffs() {
        return this.signOffs;
    }
    
    public void setSignOffs(Set signOffs) {
        this.signOffs = signOffs;
    }
    public Set getCompanyMasters() {
        return this.companyMasters;
    }
    
    public void setCompanyMasters(Set companyMasters) {
        this.companyMasters = companyMasters;
    }
    public Set getCurrentandfutureopportunitieses() {
        return this.currentandfutureopportunitieses;
    }
    
    public void setCurrentandfutureopportunitieses(Set currentandfutureopportunitieses) {
        this.currentandfutureopportunitieses = currentandfutureopportunitieses;
    }
    public Set getClientcoverageprofiles() {
        return this.clientcoverageprofiles;
    }
    
    public void setClientcoverageprofiles(Set clientcoverageprofiles) {
        this.clientcoverageprofiles = clientcoverageprofiles;
    }
    public Set getDealinprogresses() {
        return this.dealinprogresses;
    }
    
    public void setDealinprogresses(Set dealinprogresses) {
        this.dealinprogresses = dealinprogresses;
    }
    public Set getClientFinancials() {
        return this.clientFinancials;
    }
    
    public void setClientFinancials(Set clientFinancials) {
        this.clientFinancials = clientFinancials;
    }
    public Set getKeysuppliermasters() {
        return this.keysuppliermasters;
    }
    
    public void setKeysuppliermasters(Set keysuppliermasters) {
        this.keysuppliermasters = keysuppliermasters;
    }
    public Set getAccountRevenueInformations() {
        return this.accountRevenueInformations;
    }
    
    public void setAccountRevenueInformations(Set accountRevenueInformations) {
        this.accountRevenueInformations = accountRevenueInformations;
    }
    public Set getCompetitions() {
        return this.competitions;
    }
    
    public void setCompetitions(Set competitions) {
        this.competitions = competitions;
    }
    public Set getKeydistributormasters() {
        return this.keydistributormasters;
    }
    
    public void setKeydistributormasters(Set keydistributormasters) {
        this.keydistributormasters = keydistributormasters;
    }
    public Set getClientEmployees() {
        return this.clientEmployees;
    }
    
    public void setClientEmployees(Set clientEmployees) {
        this.clientEmployees = clientEmployees;
    }
    public Set getCreditInformations() {
        return this.creditInformations;
    }
    
    public void setCreditInformations(Set creditInformations) {
        this.creditInformations = creditInformations;
    }
    public Set getSalesactionplans() {
        return this.salesactionplans;
    }
    
    public void setSalesactionplans(Set salesactionplans) {
        this.salesactionplans = salesactionplans;
    }




}


