package com.inm.ap.mode.hibernate;
// Generated Jan 25, 2018 9:36:12 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ClientMaster generated by hbm2java
 */
public class ClientMaster  implements java.io.Serializable {


     private String clientid;
     private RmCodelist rmCodelistByRmCode;
     private RmCodelist rmCodelistByAlternativeRmCode;
     private Lookupmaster lookupmaster;
     private String clientname;
     private Date currentDate;
     private String tradeserviceprovider;
     private String cashmanagementpartner;
     private String EBankingpartner;
     private String riskmanagementpartner;
     
     
     private Set overallclientwalletsizes = new HashSet(0);
     private Set qualitativeinformations = new HashSet(0);
     private Set companyMasters = new HashSet(0);
     private Set clientcoverageprofiles = new HashSet(0);
     private Set dealinprogresses = new HashSet(0);
     private Set clientFinancials = new HashSet(0);
     private Set keysuppliermasters = new HashSet(0);
     private Set accountRevenueInformations = new HashSet(0);
     private Set competitions = new HashSet(0);
     private Set keydistributormasters = new HashSet(0);
     private Set clientEmployees = new HashSet(0);
     private Set creditInformations = new HashSet(0);
     private Set salesactionplans = new HashSet(0);

    public ClientMaster() {
    }

	
    public ClientMaster(String clientid, RmCodelist rmCodelistByRmCode, RmCodelist rmCodelistByAlternativeRmCode) {
        this.clientid = clientid;
        this.rmCodelistByRmCode = rmCodelistByRmCode;
        this.rmCodelistByAlternativeRmCode = rmCodelistByAlternativeRmCode;
    }
    public ClientMaster(String clientid, RmCodelist rmCodelistByRmCode, RmCodelist rmCodelistByAlternativeRmCode, Lookupmaster lookupmaster, String clientname, Date currentDate, String tradeserviceprovider, String cashmanagementpartner, String EBankingpartner, Set overallclientwalletsizes, Set qualitativeinformations, Set companyMasters, Set clientcoverageprofiles, Set dealinprogresses, Set clientFinancials, Set keysuppliermasters, Set accountRevenueInformations, Set competitions, Set keydistributormasters, Set clientEmployees, Set creditInformations, Set salesactionplans) {
       this.clientid = clientid;
       this.rmCodelistByRmCode = rmCodelistByRmCode;
       this.rmCodelistByAlternativeRmCode = rmCodelistByAlternativeRmCode;
       this.lookupmaster = lookupmaster;
       this.clientname = clientname;
       this.currentDate = currentDate;
       this.tradeserviceprovider = tradeserviceprovider;
       this.cashmanagementpartner = cashmanagementpartner;
       this.EBankingpartner = EBankingpartner;
       this.overallclientwalletsizes = overallclientwalletsizes;
       this.qualitativeinformations = qualitativeinformations;
       this.companyMasters = companyMasters;
       this.clientcoverageprofiles = clientcoverageprofiles;
       this.dealinprogresses = dealinprogresses;
       this.clientFinancials = clientFinancials;
       this.keysuppliermasters = keysuppliermasters;
       this.accountRevenueInformations = accountRevenueInformations;
       this.competitions = competitions;
       this.keydistributormasters = keydistributormasters;
       this.clientEmployees = clientEmployees;
       this.creditInformations = creditInformations;
       this.salesactionplans = salesactionplans;
    }
   
    public String getClientid() {
        return this.clientid;
    }
    
    public void setClientid(String clientid) {
        this.clientid = clientid;
    }
    public RmCodelist getRmCodelistByRmCode() {
        return this.rmCodelistByRmCode;
    }
    
    public void setRmCodelistByRmCode(RmCodelist rmCodelistByRmCode) {
        this.rmCodelistByRmCode = rmCodelistByRmCode;
    }
    public RmCodelist getRmCodelistByAlternativeRmCode() {
        return this.rmCodelistByAlternativeRmCode;
    }
    
    public void setRmCodelistByAlternativeRmCode(RmCodelist rmCodelistByAlternativeRmCode) {
        this.rmCodelistByAlternativeRmCode = rmCodelistByAlternativeRmCode;
    }
    public Lookupmaster getLookupmaster() {
        return this.lookupmaster;
    }
    
    public void setLookupmaster(Lookupmaster lookupmaster) {
        this.lookupmaster = lookupmaster;
    }
    public String getClientname() {
        return this.clientname;
    }
    
    public void setClientname(String clientname) {
        this.clientname = clientname;
    }
    public Date getCurrentDate() {
        return this.currentDate;
    }
    
    public void setCurrentDate(Date currentDate) {
        this.currentDate = currentDate;
    }
    public String getTradeserviceprovider() {
        return this.tradeserviceprovider;
    }
    
    public void setTradeserviceprovider(String tradeserviceprovider) {
        this.tradeserviceprovider = tradeserviceprovider;
    }
    public String getCashmanagementpartner() {
        return this.cashmanagementpartner;
    }
    
    public void setCashmanagementpartner(String cashmanagementpartner) {
        this.cashmanagementpartner = cashmanagementpartner;
    }
    public String getEBankingpartner() {
        return this.EBankingpartner;
    }
    
    public void setEBankingpartner(String EBankingpartner) {
        this.EBankingpartner = EBankingpartner;
    }
    public Set getOverallclientwalletsizes() {
        return this.overallclientwalletsizes;
    }
    
    public void setOverallclientwalletsizes(Set overallclientwalletsizes) {
        this.overallclientwalletsizes = overallclientwalletsizes;
    }
    public Set getQualitativeinformations() {
        return this.qualitativeinformations;
    }
    
    public void setQualitativeinformations(Set qualitativeinformations) {
        this.qualitativeinformations = qualitativeinformations;
    }
    public Set getCompanyMasters() {
        return this.companyMasters;
    }
    
    public void setCompanyMasters(Set companyMasters) {
        this.companyMasters = companyMasters;
    }
    public Set getClientcoverageprofiles() {
        return this.clientcoverageprofiles;
    }
    
    public void setClientcoverageprofiles(Set clientcoverageprofiles) {
        this.clientcoverageprofiles = clientcoverageprofiles;
    }
    public Set getDealinprogresses() {
        return this.dealinprogresses;
    }
    
    public void setDealinprogresses(Set dealinprogresses) {
        this.dealinprogresses = dealinprogresses;
    }
    public Set getClientFinancials() {
        return this.clientFinancials;
    }
    
    public void setClientFinancials(Set clientFinancials) {
        this.clientFinancials = clientFinancials;
    }
    public Set getKeysuppliermasters() {
        return this.keysuppliermasters;
    }
    
    public void setKeysuppliermasters(Set keysuppliermasters) {
        this.keysuppliermasters = keysuppliermasters;
    }
    public Set getAccountRevenueInformations() {
        return this.accountRevenueInformations;
    }
    
    public void setAccountRevenueInformations(Set accountRevenueInformations) {
        this.accountRevenueInformations = accountRevenueInformations;
    }
    public Set getCompetitions() {
        return this.competitions;
    }
    
    public void setCompetitions(Set competitions) {
        this.competitions = competitions;
    }
    public Set getKeydistributormasters() {
        return this.keydistributormasters;
    }
    
    public void setKeydistributormasters(Set keydistributormasters) {
        this.keydistributormasters = keydistributormasters;
    }
    public Set getClientEmployees() {
        return this.clientEmployees;
    }
    
    public void setClientEmployees(Set clientEmployees) {
        this.clientEmployees = clientEmployees;
    }
    public Set getCreditInformations() {
        return this.creditInformations;
    }
    
    public void setCreditInformations(Set creditInformations) {
        this.creditInformations = creditInformations;
    }
    public Set getSalesactionplans() {
        return this.salesactionplans;
    }
    
    public void setSalesactionplans(Set salesactionplans) {
        this.salesactionplans = salesactionplans;
    }

    public String getRiskmanagementpartner() {
        return riskmanagementpartner;
    }

    public void setRiskmanagementpartner(String riskmanagementpartner) {
        this.riskmanagementpartner = riskmanagementpartner;
    }




}


