package com.inm.ap.mode.hibernate;
// Generated Feb 19, 2018 4:06:43 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * ClientEmployee generated by hbm2java
 */
public class ClientEmployee  implements java.io.Serializable {


     private int clientemployeeid;
     private Lookupmaster lookupmaster;
     private ClientMaster clientMaster;
     private String clientEmployeeContactperson;
     private String clientEmployeePhonenumber;
     private String clientEmployeeEmail;
     private String clientEmployeeLocation;
     private String noofemployees;
     private String noofbankedemployeesallbanks;
     private String noofbankedemployeeswithim;
     private String targetnoofemployeesbyim;

    public ClientEmployee() {
    }

	
    public ClientEmployee(int clientemployeeid, Lookupmaster lookupmaster, ClientMaster clientMaster) {
        this.clientemployeeid = clientemployeeid;
        this.lookupmaster = lookupmaster;
        this.clientMaster = clientMaster;
    }
    public ClientEmployee(int clientemployeeid, Lookupmaster lookupmaster, ClientMaster clientMaster, String clientEmployeeContactperson, String clientEmployeePhonenumber, String clientEmployeeEmail, String clientEmployeeLocation, String noofemployees, String noofbankedemployeesallbanks, String noofbankedemployeeswithim, String targetnoofemployeesbyim) {
       this.clientemployeeid = clientemployeeid;
       this.lookupmaster = lookupmaster;
       this.clientMaster = clientMaster;
       this.clientEmployeeContactperson = clientEmployeeContactperson;
       this.clientEmployeePhonenumber = clientEmployeePhonenumber;
       this.clientEmployeeEmail = clientEmployeeEmail;
       this.clientEmployeeLocation = clientEmployeeLocation;
       this.noofemployees = noofemployees;
       this.noofbankedemployeesallbanks = noofbankedemployeesallbanks;
       this.noofbankedemployeeswithim = noofbankedemployeeswithim;
       this.targetnoofemployeesbyim = targetnoofemployeesbyim;
    }
   
    public int getClientemployeeid() {
        return this.clientemployeeid;
    }
    
    public void setClientemployeeid(int clientemployeeid) {
        this.clientemployeeid = clientemployeeid;
    }
    public Lookupmaster getLookupmaster() {
        return this.lookupmaster;
    }
    
    public void setLookupmaster(Lookupmaster lookupmaster) {
        this.lookupmaster = lookupmaster;
    }
    public ClientMaster getClientMaster() {
        return this.clientMaster;
    }
    
    public void setClientMaster(ClientMaster clientMaster) {
        this.clientMaster = clientMaster;
    }
    public String getClientEmployeeContactperson() {
        return this.clientEmployeeContactperson;
    }
    
    public void setClientEmployeeContactperson(String clientEmployeeContactperson) {
        this.clientEmployeeContactperson = clientEmployeeContactperson;
    }
    public String getClientEmployeePhonenumber() {
        return this.clientEmployeePhonenumber;
    }
    
    public void setClientEmployeePhonenumber(String clientEmployeePhonenumber) {
        this.clientEmployeePhonenumber = clientEmployeePhonenumber;
    }
    public String getClientEmployeeEmail() {
        return this.clientEmployeeEmail;
    }
    
    public void setClientEmployeeEmail(String clientEmployeeEmail) {
        this.clientEmployeeEmail = clientEmployeeEmail;
    }
    public String getClientEmployeeLocation() {
        return this.clientEmployeeLocation;
    }
    
    public void setClientEmployeeLocation(String clientEmployeeLocation) {
        this.clientEmployeeLocation = clientEmployeeLocation;
    }
    public String getNoofemployees() {
        return this.noofemployees;
    }
    
    public void setNoofemployees(String noofemployees) {
        this.noofemployees = noofemployees;
    }
    public String getNoofbankedemployeesallbanks() {
        return this.noofbankedemployeesallbanks;
    }
    
    public void setNoofbankedemployeesallbanks(String noofbankedemployeesallbanks) {
        this.noofbankedemployeesallbanks = noofbankedemployeesallbanks;
    }
    public String getNoofbankedemployeeswithim() {
        return this.noofbankedemployeeswithim;
    }
    
    public void setNoofbankedemployeeswithim(String noofbankedemployeeswithim) {
        this.noofbankedemployeeswithim = noofbankedemployeeswithim;
    }
    public String getTargetnoofemployeesbyim() {
        return this.targetnoofemployeesbyim;
    }
    
    public void setTargetnoofemployeesbyim(String targetnoofemployeesbyim) {
        this.targetnoofemployeesbyim = targetnoofemployeesbyim;
    }




}


