package com.inm.ap.mode.hibernate;
// Generated Feb 21, 2018 4:01:48 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * CompanyDirectors generated by hbm2java
 */
public class CompanyDirectors  implements java.io.Serializable {


     private int companyDirectorsId;
     private CompanyMaster companyMaster;
     private String directorName;
     private String directorPosition;

    public CompanyDirectors() {
    }

	
    public CompanyDirectors(int companyDirectorsId, CompanyMaster companyMaster) {
        this.companyDirectorsId = companyDirectorsId;
        this.companyMaster = companyMaster;
    }
    public CompanyDirectors(int companyDirectorsId, CompanyMaster companyMaster, String directorName, String directorPosition) {
       this.companyDirectorsId = companyDirectorsId;
       this.companyMaster = companyMaster;
       this.directorName = directorName;
       this.directorPosition = directorPosition;
    }
   
    public int getCompanyDirectorsId() {
        return this.companyDirectorsId;
    }
    
    public void setCompanyDirectorsId(int companyDirectorsId) {
        this.companyDirectorsId = companyDirectorsId;
    }
    public CompanyMaster getCompanyMaster() {
        return this.companyMaster;
    }
    
    public void setCompanyMaster(CompanyMaster companyMaster) {
        this.companyMaster = companyMaster;
    }
    public String getDirectorName() {
        return this.directorName;
    }
    
    public void setDirectorName(String directorName) {
        this.directorName = directorName;
    }
    public String getDirectorPosition() {
        return this.directorPosition;
    }
    
    public void setDirectorPosition(String directorPosition) {
        this.directorPosition = directorPosition;
    }




}


