package com.inm.ap.mode.hibernate;
// Generated Feb 21, 2018 4:01:48 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * CompanyShareholders generated by hbm2java
 */
public class CompanyShareholders  implements java.io.Serializable {


     private int sharedolderId;
     private CompanyMaster companyMaster;
     private String shareholderName;
     private BigDecimal shareholderPercent;

    public CompanyShareholders() {
    }

	
    public CompanyShareholders(int sharedolderId) {
        this.sharedolderId = sharedolderId;
    }
    public CompanyShareholders(int sharedolderId, CompanyMaster companyMaster, String shareholderName, BigDecimal shareholderPercent) {
       this.sharedolderId = sharedolderId;
       this.companyMaster = companyMaster;
       this.shareholderName = shareholderName;
       this.shareholderPercent = shareholderPercent;
    }
   
    public int getSharedolderId() {
        return this.sharedolderId;
    }
    
    public void setSharedolderId(int sharedolderId) {
        this.sharedolderId = sharedolderId;
    }
    public CompanyMaster getCompanyMaster() {
        return this.companyMaster;
    }
    
    public void setCompanyMaster(CompanyMaster companyMaster) {
        this.companyMaster = companyMaster;
    }
    public String getShareholderName() {
        return this.shareholderName;
    }
    
    public void setShareholderName(String shareholderName) {
        this.shareholderName = shareholderName;
    }
    public BigDecimal getShareholderPercent() {
        return this.shareholderPercent;
    }
    
    public void setShareholderPercent(BigDecimal shareholderPercent) {
        this.shareholderPercent = shareholderPercent;
    }




}


