package com.inm.ap.mode.hibernate;
// Generated Jan 25, 2018 9:36:12 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * CompanyMaster generated by hbm2java
 */
public class CompanyMaster  implements java.io.Serializable {


     private int companyid;
     private Lookupmaster lookupmasterByIndustrylookupmasterid;
     private Lookupmaster lookupmasterByAffiliatelookupmasterid;
     private Lookupmaster lookupmasterBySegmentlookupmasterid;
     private ClientMaster clientMaster;
     private String companyAddress;
     private String groupname;
     private int noofsubsidiaries;

    public CompanyMaster() {
    }

	
    public CompanyMaster(int companyid, Lookupmaster lookupmasterByIndustrylookupmasterid, Lookupmaster lookupmasterByAffiliatelookupmasterid, Lookupmaster lookupmasterBySegmentlookupmasterid, ClientMaster clientMaster) {
        this.companyid = companyid;
        this.lookupmasterByIndustrylookupmasterid = lookupmasterByIndustrylookupmasterid;
        this.lookupmasterByAffiliatelookupmasterid = lookupmasterByAffiliatelookupmasterid;
        this.lookupmasterBySegmentlookupmasterid = lookupmasterBySegmentlookupmasterid;
        this.clientMaster = clientMaster;
    }
    public CompanyMaster(int companyid, Lookupmaster lookupmasterByIndustrylookupmasterid, Lookupmaster lookupmasterByAffiliatelookupmasterid, Lookupmaster lookupmasterBySegmentlookupmasterid, ClientMaster clientMaster, String companyAddress, String groupname, int noofsubsidiaries) {
       this.companyid = companyid;
       this.lookupmasterByIndustrylookupmasterid = lookupmasterByIndustrylookupmasterid;
       this.lookupmasterByAffiliatelookupmasterid = lookupmasterByAffiliatelookupmasterid;
       this.lookupmasterBySegmentlookupmasterid = lookupmasterBySegmentlookupmasterid;
       this.clientMaster = clientMaster;
       this.companyAddress = companyAddress;
       this.groupname = groupname;
       this.noofsubsidiaries = noofsubsidiaries;
    }
   
    public int getCompanyid() {
        return this.companyid;
    }
    
    public void setCompanyid(int companyid) {
        this.companyid = companyid;
    }
    public Lookupmaster getLookupmasterByIndustrylookupmasterid() {
        return this.lookupmasterByIndustrylookupmasterid;
    }
    
    public void setLookupmasterByIndustrylookupmasterid(Lookupmaster lookupmasterByIndustrylookupmasterid) {
        this.lookupmasterByIndustrylookupmasterid = lookupmasterByIndustrylookupmasterid;
    }
    public Lookupmaster getLookupmasterByAffiliatelookupmasterid() {
        return this.lookupmasterByAffiliatelookupmasterid;
    }
    
    public void setLookupmasterByAffiliatelookupmasterid(Lookupmaster lookupmasterByAffiliatelookupmasterid) {
        this.lookupmasterByAffiliatelookupmasterid = lookupmasterByAffiliatelookupmasterid;
    }
    public Lookupmaster getLookupmasterBySegmentlookupmasterid() {
        return this.lookupmasterBySegmentlookupmasterid;
    }
    
    public void setLookupmasterBySegmentlookupmasterid(Lookupmaster lookupmasterBySegmentlookupmasterid) {
        this.lookupmasterBySegmentlookupmasterid = lookupmasterBySegmentlookupmasterid;
    }
    public ClientMaster getClientMaster() {
        return this.clientMaster;
    }
    
    public void setClientMaster(ClientMaster clientMaster) {
        this.clientMaster = clientMaster;
    }
    public String getCompanyAddress() {
        return this.companyAddress;
    }
    
    public void setCompanyAddress(String companyAddress) {
        this.companyAddress = companyAddress;
    }
    public String getGroupname() {
        return this.groupname;
    }
    
    public void setGroupname(String groupname) {
        this.groupname = groupname;
    }
    public int getNoofsubsidiaries() {
        return this.noofsubsidiaries;
    }
    
    public void setNoofsubsidiaries(int noofsubsidiaries) {
        this.noofsubsidiaries = noofsubsidiaries;
    }




}


