package com.inm.ap.mode.hibernate;
// Generated Jan 31, 2018 3:59:00 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Competition generated by hbm2java
 */
public class Competition  implements java.io.Serializable {


     private int competitionid;
     private ClientMaster clientMaster;
     private String bank;
     private String estimatedwalletshare;
     private String strengths;
     private String weaknesses;

    public Competition() {
    }

	
    public Competition(int competitionid) {
        this.competitionid = competitionid;
    }
    public Competition(int competitionid, ClientMaster clientMaster, String bank, String estimatedwalletshare, String strengths, String weaknesses) {
       this.competitionid = competitionid;
       this.clientMaster = clientMaster;
       this.bank = bank;
       this.estimatedwalletshare = estimatedwalletshare;
       this.strengths = strengths;
       this.weaknesses = weaknesses;
    }
   
    public int getCompetitionid() {
        return this.competitionid;
    }
    
    public void setCompetitionid(int competitionid) {
        this.competitionid = competitionid;
    }
    public ClientMaster getClientMaster() {
        return this.clientMaster;
    }
    
    public void setClientMaster(ClientMaster clientMaster) {
        this.clientMaster = clientMaster;
    }
    public String getBank() {
        return this.bank;
    }
    
    public void setBank(String bank) {
        this.bank = bank;
    }
    public String getEstimatedwalletshare() {
        return this.estimatedwalletshare;
    }
    
    public void setEstimatedwalletshare(String estimatedwalletshare) {
        this.estimatedwalletshare = estimatedwalletshare;
    }
    public String getStrengths() {
        return this.strengths;
    }
    
    public void setStrengths(String strengths) {
        this.strengths = strengths;
    }
    public String getWeaknesses() {
        return this.weaknesses;
    }
    
    public void setWeaknesses(String weaknesses) {
        this.weaknesses = weaknesses;
    }




}


