package com.inm.ap.mode.hibernate;
// Generated Feb 19, 2018 4:06:43 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * CustomerTracking generated by hbm2java
 */
public class CustomerTracking  implements java.io.Serializable {


     private String id;
     private BigDecimal customerId;
     private String filledDate;
     private String filledWeek;
     private String clientContacted;
     private String salesCommitment;
     private String docsSubmitted;
     private String closed;
     private String comments;
     private String productSold;
     private String rmCode;
     private BigDecimal bmCode;
     private Double regionalManagerCode;
     private String branch;
     private BigDecimal productValue;
     private String customerType;
     private Double bmCodeSustainability;
     private Double regmCodeSustainability;
     private String currentWeek;
     private String currency;
     private BigDecimal marketedValue;
     private String leadSource;
     private String productCategory;

    public CustomerTracking() {
    }

	
    public CustomerTracking(String id, BigDecimal customerId) {
        this.id = id;
        this.customerId = customerId;
    }
    public CustomerTracking(String id, BigDecimal customerId, String filledDate, String filledWeek, String clientContacted, String salesCommitment, String docsSubmitted, String closed, String comments, String productSold, String rmCode, BigDecimal bmCode, Double regionalManagerCode, String branch, BigDecimal productValue, String customerType, Double bmCodeSustainability, Double regmCodeSustainability, String currentWeek, String currency, BigDecimal marketedValue, String leadSource, String productCategory) {
       this.id = id;
       this.customerId = customerId;
       this.filledDate = filledDate;
       this.filledWeek = filledWeek;
       this.clientContacted = clientContacted;
       this.salesCommitment = salesCommitment;
       this.docsSubmitted = docsSubmitted;
       this.closed = closed;
       this.comments = comments;
       this.productSold = productSold;
       this.rmCode = rmCode;
       this.bmCode = bmCode;
       this.regionalManagerCode = regionalManagerCode;
       this.branch = branch;
       this.productValue = productValue;
       this.customerType = customerType;
       this.bmCodeSustainability = bmCodeSustainability;
       this.regmCodeSustainability = regmCodeSustainability;
       this.currentWeek = currentWeek;
       this.currency = currency;
       this.marketedValue = marketedValue;
       this.leadSource = leadSource;
       this.productCategory = productCategory;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public BigDecimal getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(BigDecimal customerId) {
        this.customerId = customerId;
    }
    public String getFilledDate() {
        return this.filledDate;
    }
    
    public void setFilledDate(String filledDate) {
        this.filledDate = filledDate;
    }
    public String getFilledWeek() {
        return this.filledWeek;
    }
    
    public void setFilledWeek(String filledWeek) {
        this.filledWeek = filledWeek;
    }
    public String getClientContacted() {
        return this.clientContacted;
    }
    
    public void setClientContacted(String clientContacted) {
        this.clientContacted = clientContacted;
    }
    public String getSalesCommitment() {
        return this.salesCommitment;
    }
    
    public void setSalesCommitment(String salesCommitment) {
        this.salesCommitment = salesCommitment;
    }
    public String getDocsSubmitted() {
        return this.docsSubmitted;
    }
    
    public void setDocsSubmitted(String docsSubmitted) {
        this.docsSubmitted = docsSubmitted;
    }
    public String getClosed() {
        return this.closed;
    }
    
    public void setClosed(String closed) {
        this.closed = closed;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    public String getProductSold() {
        return this.productSold;
    }
    
    public void setProductSold(String productSold) {
        this.productSold = productSold;
    }
    public String getRmCode() {
        return this.rmCode;
    }
    
    public void setRmCode(String rmCode) {
        this.rmCode = rmCode;
    }
    public BigDecimal getBmCode() {
        return this.bmCode;
    }
    
    public void setBmCode(BigDecimal bmCode) {
        this.bmCode = bmCode;
    }
    public Double getRegionalManagerCode() {
        return this.regionalManagerCode;
    }
    
    public void setRegionalManagerCode(Double regionalManagerCode) {
        this.regionalManagerCode = regionalManagerCode;
    }
    public String getBranch() {
        return this.branch;
    }
    
    public void setBranch(String branch) {
        this.branch = branch;
    }
    public BigDecimal getProductValue() {
        return this.productValue;
    }
    
    public void setProductValue(BigDecimal productValue) {
        this.productValue = productValue;
    }
    public String getCustomerType() {
        return this.customerType;
    }
    
    public void setCustomerType(String customerType) {
        this.customerType = customerType;
    }
    public Double getBmCodeSustainability() {
        return this.bmCodeSustainability;
    }
    
    public void setBmCodeSustainability(Double bmCodeSustainability) {
        this.bmCodeSustainability = bmCodeSustainability;
    }
    public Double getRegmCodeSustainability() {
        return this.regmCodeSustainability;
    }
    
    public void setRegmCodeSustainability(Double regmCodeSustainability) {
        this.regmCodeSustainability = regmCodeSustainability;
    }
    public String getCurrentWeek() {
        return this.currentWeek;
    }
    
    public void setCurrentWeek(String currentWeek) {
        this.currentWeek = currentWeek;
    }
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }
    public BigDecimal getMarketedValue() {
        return this.marketedValue;
    }
    
    public void setMarketedValue(BigDecimal marketedValue) {
        this.marketedValue = marketedValue;
    }
    public String getLeadSource() {
        return this.leadSource;
    }
    
    public void setLeadSource(String leadSource) {
        this.leadSource = leadSource;
    }
    public String getProductCategory() {
        return this.productCategory;
    }
    
    public void setProductCategory(String productCategory) {
        this.productCategory = productCategory;
    }




}


