package com.inm.ap.mode.hibernate;
// Generated Jan 25, 2018 9:36:12 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * EmployeeLeave generated by hbm2java
 */
public class EmployeeLeave  implements java.io.Serializable {


     private BigDecimal leaveid;
     private RmCodelist rmCodelist;
     private String rmname;
     private String leavetype;
     private Date startdate;
     private Date enddate;
     private String comments;

    public EmployeeLeave() {
    }

	
    public EmployeeLeave(BigDecimal leaveid) {
        this.leaveid = leaveid;
    }
    public EmployeeLeave(BigDecimal leaveid, RmCodelist rmCodelist, String rmname, String leavetype, Date startdate, Date enddate, String comments) {
       this.leaveid = leaveid;
       this.rmCodelist = rmCodelist;
       this.rmname = rmname;
       this.leavetype = leavetype;
       this.startdate = startdate;
       this.enddate = enddate;
       this.comments = comments;
    }
   
    public BigDecimal getLeaveid() {
        return this.leaveid;
    }
    
    public void setLeaveid(BigDecimal leaveid) {
        this.leaveid = leaveid;
    }
    public RmCodelist getRmCodelist() {
        return this.rmCodelist;
    }
    
    public void setRmCodelist(RmCodelist rmCodelist) {
        this.rmCodelist = rmCodelist;
    }
    public String getRmname() {
        return this.rmname;
    }
    
    public void setRmname(String rmname) {
        this.rmname = rmname;
    }
    public String getLeavetype() {
        return this.leavetype;
    }
    
    public void setLeavetype(String leavetype) {
        this.leavetype = leavetype;
    }
    public Date getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }
    public Date getEnddate() {
        return this.enddate;
    }
    
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }




}


