package com.inm.ap.mode.hibernate;
// Generated Jan 25, 2018 9:36:12 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * ExcaliburUsage generated by hbm2java
 */
public class ExcaliburUsage  implements java.io.Serializable {


     private String usageid;
     private BigDecimal employeeid;
     private Date logintime;
     private String logouttime;

    public ExcaliburUsage() {
    }

	
    public ExcaliburUsage(String usageid) {
        this.usageid = usageid;
    }
    public ExcaliburUsage(String usageid, BigDecimal employeeid, Date logintime, String logouttime) {
       this.usageid = usageid;
       this.employeeid = employeeid;
       this.logintime = logintime;
       this.logouttime = logouttime;
    }
   
    public String getUsageid() {
        return this.usageid;
    }
    
    public void setUsageid(String usageid) {
        this.usageid = usageid;
    }
    public BigDecimal getEmployeeid() {
        return this.employeeid;
    }
    
    public void setEmployeeid(BigDecimal employeeid) {
        this.employeeid = employeeid;
    }
    public Date getLogintime() {
        return this.logintime;
    }
    
    public void setLogintime(Date logintime) {
        this.logintime = logintime;
    }
    public String getLogouttime() {
        return this.logouttime;
    }
    
    public void setLogouttime(String logouttime) {
        this.logouttime = logouttime;
    }




}


