package com.inm.ap.mode.hibernate;
// Generated Feb 19, 2018 4:06:43 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Fpt generated by hbm2java
 */
public class Fpt  implements java.io.Serializable {


     private int fptId;
     private BigDecimal tenorStart;
     private BigDecimal tenorEnd;
     private BigDecimal debitPoolRate;
     private BigDecimal creditPoolRate;

    public Fpt() {
    }

	
    public Fpt(int fptId) {
        this.fptId = fptId;
    }
    public Fpt(int fptId, BigDecimal tenorStart, BigDecimal tenorEnd, BigDecimal debitPoolRate, BigDecimal creditPoolRate) {
       this.fptId = fptId;
       this.tenorStart = tenorStart;
       this.tenorEnd = tenorEnd;
       this.debitPoolRate = debitPoolRate;
       this.creditPoolRate = creditPoolRate;
    }
   
    public int getFptId() {
        return this.fptId;
    }
    
    public void setFptId(int fptId) {
        this.fptId = fptId;
    }
    public BigDecimal getTenorStart() {
        return this.tenorStart;
    }
    
    public void setTenorStart(BigDecimal tenorStart) {
        this.tenorStart = tenorStart;
    }
    public BigDecimal getTenorEnd() {
        return this.tenorEnd;
    }
    
    public void setTenorEnd(BigDecimal tenorEnd) {
        this.tenorEnd = tenorEnd;
    }
    public BigDecimal getDebitPoolRate() {
        return this.debitPoolRate;
    }
    
    public void setDebitPoolRate(BigDecimal debitPoolRate) {
        this.debitPoolRate = debitPoolRate;
    }
    public BigDecimal getCreditPoolRate() {
        return this.creditPoolRate;
    }
    
    public void setCreditPoolRate(BigDecimal creditPoolRate) {
        this.creditPoolRate = creditPoolRate;
    }




}


