package com.inm.ap.mode.hibernate;
// Generated Feb 19, 2018 4:06:43 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Keysuppliermaster generated by hbm2java
 */
public class Keysuppliermaster  implements java.io.Serializable {


     private int ksid;
     private Lookupmaster lookupmaster;
     private ClientMaster clientMaster;
     private String ksname;
     private String ksContactperson;
     private String ksPhonenumber;
     private String ksEmail;
     private String ksLocation;
     private String volofbusiness;
     private String bankedbyim;
     private String comments;

    public Keysuppliermaster() {
    }

	
    public Keysuppliermaster(int ksid, Lookupmaster lookupmaster, ClientMaster clientMaster) {
        this.ksid = ksid;
        this.lookupmaster = lookupmaster;
        this.clientMaster = clientMaster;
    }
    public Keysuppliermaster(int ksid, Lookupmaster lookupmaster, ClientMaster clientMaster, String ksname, String ksContactperson, String ksPhonenumber, String ksEmail, String ksLocation, String volofbusiness, String bankedbyim, String comments) {
       this.ksid = ksid;
       this.lookupmaster = lookupmaster;
       this.clientMaster = clientMaster;
       this.ksname = ksname;
       this.ksContactperson = ksContactperson;
       this.ksPhonenumber = ksPhonenumber;
       this.ksEmail = ksEmail;
       this.ksLocation = ksLocation;
       this.volofbusiness = volofbusiness;
       this.bankedbyim = bankedbyim;
       this.comments = comments;
    }
   
    public int getKsid() {
        return this.ksid;
    }
    
    public void setKsid(int ksid) {
        this.ksid = ksid;
    }
    public Lookupmaster getLookupmaster() {
        return this.lookupmaster;
    }
    
    public void setLookupmaster(Lookupmaster lookupmaster) {
        this.lookupmaster = lookupmaster;
    }
    public ClientMaster getClientMaster() {
        return this.clientMaster;
    }
    
    public void setClientMaster(ClientMaster clientMaster) {
        this.clientMaster = clientMaster;
    }
    public String getKsname() {
        return this.ksname;
    }
    
    public void setKsname(String ksname) {
        this.ksname = ksname;
    }
    public String getKsContactperson() {
        return this.ksContactperson;
    }
    
    public void setKsContactperson(String ksContactperson) {
        this.ksContactperson = ksContactperson;
    }
    public String getKsPhonenumber() {
        return this.ksPhonenumber;
    }
    
    public void setKsPhonenumber(String ksPhonenumber) {
        this.ksPhonenumber = ksPhonenumber;
    }
    public String getKsEmail() {
        return this.ksEmail;
    }
    
    public void setKsEmail(String ksEmail) {
        this.ksEmail = ksEmail;
    }
    public String getKsLocation() {
        return this.ksLocation;
    }
    
    public void setKsLocation(String ksLocation) {
        this.ksLocation = ksLocation;
    }
    public String getVolofbusiness() {
        return this.volofbusiness;
    }
    
    public void setVolofbusiness(String volofbusiness) {
        this.volofbusiness = volofbusiness;
    }
    public String getBankedbyim() {
        return this.bankedbyim;
    }
    
    public void setBankedbyim(String bankedbyim) {
        this.bankedbyim = bankedbyim;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }




}


