package com.inm.ap.mode.hibernate;
// Generated Jan 25, 2018 9:36:12 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Lookupmaster generated by hbm2java
 */
public class Lookupmaster  implements java.io.Serializable {


     private int lookupmasterid;
     private String code;
     private String value;
     private Set clientEmployees = new HashSet(0);
     private Set clientMasters = new HashSet(0);
     private Set dealinprogressesForDealpropabilitylookupid = new HashSet(0);
     private Set dealinprogressesForProductlookupid = new HashSet(0);
     private Set companyMastersForIndustrylookupmasterid = new HashSet(0);
     private Set companyMastersForAffiliatelookupmasterid = new HashSet(0);
     private Set companyMastersForSegmentlookupmasterid = new HashSet(0);
     private Set dealinprogressesForDealstagelookupmasterid = new HashSet(0);
     private Set dealinprogressesForCompletionmonthlookupid = new HashSet(0);
     private Set keysuppliermasters = new HashSet(0);
     private Set dealinprogressesForDealstatuslookupmasterid = new HashSet(0);
     private Set keydistributormasters = new HashSet(0);
     private Set dealinprogressesForDealtypelookupmasterid = new HashSet(0);

    public Lookupmaster() {
    }

	
    public Lookupmaster(int lookupmasterid, String code, String value) {
        this.lookupmasterid = lookupmasterid;
        this.code = code;
        this.value = value;
    }
    public Lookupmaster(int lookupmasterid, String code, String value, Set clientEmployees, Set clientMasters, Set dealinprogressesForDealpropabilitylookupid, Set dealinprogressesForProductlookupid, Set companyMastersForIndustrylookupmasterid, Set companyMastersForAffiliatelookupmasterid, Set companyMastersForSegmentlookupmasterid, Set dealinprogressesForDealstagelookupmasterid, Set dealinprogressesForCompletionmonthlookupid, Set keysuppliermasters, Set dealinprogressesForDealstatuslookupmasterid, Set keydistributormasters, Set dealinprogressesForDealtypelookupmasterid) {
       this.lookupmasterid = lookupmasterid;
       this.code = code;
       this.value = value;
       this.clientEmployees = clientEmployees;
       this.clientMasters = clientMasters;
       this.dealinprogressesForDealpropabilitylookupid = dealinprogressesForDealpropabilitylookupid;
       this.dealinprogressesForProductlookupid = dealinprogressesForProductlookupid;
       this.companyMastersForIndustrylookupmasterid = companyMastersForIndustrylookupmasterid;
       this.companyMastersForAffiliatelookupmasterid = companyMastersForAffiliatelookupmasterid;
       this.companyMastersForSegmentlookupmasterid = companyMastersForSegmentlookupmasterid;
       this.dealinprogressesForDealstagelookupmasterid = dealinprogressesForDealstagelookupmasterid;
       this.dealinprogressesForCompletionmonthlookupid = dealinprogressesForCompletionmonthlookupid;
       this.keysuppliermasters = keysuppliermasters;
       this.dealinprogressesForDealstatuslookupmasterid = dealinprogressesForDealstatuslookupmasterid;
       this.keydistributormasters = keydistributormasters;
       this.dealinprogressesForDealtypelookupmasterid = dealinprogressesForDealtypelookupmasterid;
    }
   
    public int getLookupmasterid() {
        return this.lookupmasterid;
    }
    
    public void setLookupmasterid(int lookupmasterid) {
        this.lookupmasterid = lookupmasterid;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public Set getClientEmployees() {
        return this.clientEmployees;
    }
    
    public void setClientEmployees(Set clientEmployees) {
        this.clientEmployees = clientEmployees;
    }
    public Set getClientMasters() {
        return this.clientMasters;
    }
    
    public void setClientMasters(Set clientMasters) {
        this.clientMasters = clientMasters;
    }
    public Set getDealinprogressesForDealpropabilitylookupid() {
        return this.dealinprogressesForDealpropabilitylookupid;
    }
    
    public void setDealinprogressesForDealpropabilitylookupid(Set dealinprogressesForDealpropabilitylookupid) {
        this.dealinprogressesForDealpropabilitylookupid = dealinprogressesForDealpropabilitylookupid;
    }
    public Set getDealinprogressesForProductlookupid() {
        return this.dealinprogressesForProductlookupid;
    }
    
    public void setDealinprogressesForProductlookupid(Set dealinprogressesForProductlookupid) {
        this.dealinprogressesForProductlookupid = dealinprogressesForProductlookupid;
    }
    public Set getCompanyMastersForIndustrylookupmasterid() {
        return this.companyMastersForIndustrylookupmasterid;
    }
    
    public void setCompanyMastersForIndustrylookupmasterid(Set companyMastersForIndustrylookupmasterid) {
        this.companyMastersForIndustrylookupmasterid = companyMastersForIndustrylookupmasterid;
    }
    public Set getCompanyMastersForAffiliatelookupmasterid() {
        return this.companyMastersForAffiliatelookupmasterid;
    }
    
    public void setCompanyMastersForAffiliatelookupmasterid(Set companyMastersForAffiliatelookupmasterid) {
        this.companyMastersForAffiliatelookupmasterid = companyMastersForAffiliatelookupmasterid;
    }
    public Set getCompanyMastersForSegmentlookupmasterid() {
        return this.companyMastersForSegmentlookupmasterid;
    }
    
    public void setCompanyMastersForSegmentlookupmasterid(Set companyMastersForSegmentlookupmasterid) {
        this.companyMastersForSegmentlookupmasterid = companyMastersForSegmentlookupmasterid;
    }
    public Set getDealinprogressesForDealstagelookupmasterid() {
        return this.dealinprogressesForDealstagelookupmasterid;
    }
    
    public void setDealinprogressesForDealstagelookupmasterid(Set dealinprogressesForDealstagelookupmasterid) {
        this.dealinprogressesForDealstagelookupmasterid = dealinprogressesForDealstagelookupmasterid;
    }
    public Set getDealinprogressesForCompletionmonthlookupid() {
        return this.dealinprogressesForCompletionmonthlookupid;
    }
    
    public void setDealinprogressesForCompletionmonthlookupid(Set dealinprogressesForCompletionmonthlookupid) {
        this.dealinprogressesForCompletionmonthlookupid = dealinprogressesForCompletionmonthlookupid;
    }
    public Set getKeysuppliermasters() {
        return this.keysuppliermasters;
    }
    
    public void setKeysuppliermasters(Set keysuppliermasters) {
        this.keysuppliermasters = keysuppliermasters;
    }
    public Set getDealinprogressesForDealstatuslookupmasterid() {
        return this.dealinprogressesForDealstatuslookupmasterid;
    }
    
    public void setDealinprogressesForDealstatuslookupmasterid(Set dealinprogressesForDealstatuslookupmasterid) {
        this.dealinprogressesForDealstatuslookupmasterid = dealinprogressesForDealstatuslookupmasterid;
    }
    public Set getKeydistributormasters() {
        return this.keydistributormasters;
    }
    
    public void setKeydistributormasters(Set keydistributormasters) {
        this.keydistributormasters = keydistributormasters;
    }
    public Set getDealinprogressesForDealtypelookupmasterid() {
        return this.dealinprogressesForDealtypelookupmasterid;
    }
    
    public void setDealinprogressesForDealtypelookupmasterid(Set dealinprogressesForDealtypelookupmasterid) {
        this.dealinprogressesForDealtypelookupmasterid = dealinprogressesForDealtypelookupmasterid;
    }




}


