package com.inm.ap.mode.hibernate;
// Generated Feb 19, 2018 4:06:43 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Qualitativeinformation generated by hbm2java
 */
public class Qualitativeinformation  implements java.io.Serializable {


     private int qinfoid;
     private ClientMaster clientMaster;
     private String clientstrategy;
     private String clientwalletalloctnlogic;
     private String opportunities;
     private String specificchallenges;
     private String relationshipquality;

    public Qualitativeinformation() {
    }

	
    public Qualitativeinformation(int qinfoid, ClientMaster clientMaster) {
        this.qinfoid = qinfoid;
        this.clientMaster = clientMaster;
    }
    public Qualitativeinformation(int qinfoid, ClientMaster clientMaster, String clientstrategy, String clientwalletalloctnlogic, String opportunities, String specificchallenges, String relationshipquality) {
       this.qinfoid = qinfoid;
       this.clientMaster = clientMaster;
       this.clientstrategy = clientstrategy;
       this.clientwalletalloctnlogic = clientwalletalloctnlogic;
       this.opportunities = opportunities;
       this.specificchallenges = specificchallenges;
       this.relationshipquality = relationshipquality;
    }
   
    public int getQinfoid() {
        return this.qinfoid;
    }
    
    public void setQinfoid(int qinfoid) {
        this.qinfoid = qinfoid;
    }
    public ClientMaster getClientMaster() {
        return this.clientMaster;
    }
    
    public void setClientMaster(ClientMaster clientMaster) {
        this.clientMaster = clientMaster;
    }
    public String getClientstrategy() {
        return this.clientstrategy;
    }
    
    public void setClientstrategy(String clientstrategy) {
        this.clientstrategy = clientstrategy;
    }
    public String getClientwalletalloctnlogic() {
        return this.clientwalletalloctnlogic;
    }
    
    public void setClientwalletalloctnlogic(String clientwalletalloctnlogic) {
        this.clientwalletalloctnlogic = clientwalletalloctnlogic;
    }
    public String getOpportunities() {
        return this.opportunities;
    }
    
    public void setOpportunities(String opportunities) {
        this.opportunities = opportunities;
    }
    public String getSpecificchallenges() {
        return this.specificchallenges;
    }
    
    public void setSpecificchallenges(String specificchallenges) {
        this.specificchallenges = specificchallenges;
    }
    public String getRelationshipquality() {
        return this.relationshipquality;
    }
    
    public void setRelationshipquality(String relationshipquality) {
        this.relationshipquality = relationshipquality;
    }




}


