package com.inm.ap.mode.hibernate;
// Generated Feb 19, 2018 4:06:43 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Salesactionplan generated by hbm2java
 */
public class Salesactionplan  implements java.io.Serializable {


     private int salesactionplanid;
     private ClientMaster clientMaster;
     private String specificAction;
     private String clocontactpersion;
     private String clopersonresponsibleforaction;
     private String clodeadlinedate;

    public Salesactionplan() {
    }

	
    public Salesactionplan(int salesactionplanid, ClientMaster clientMaster) {
        this.salesactionplanid = salesactionplanid;
        this.clientMaster = clientMaster;
    }
    public Salesactionplan(int salesactionplanid, ClientMaster clientMaster, String specificAction, String clocontactpersion, String clopersonresponsibleforaction, String clodeadlinedate) {
       this.salesactionplanid = salesactionplanid;
       this.clientMaster = clientMaster;
       this.specificAction = specificAction;
       this.clocontactpersion = clocontactpersion;
       this.clopersonresponsibleforaction = clopersonresponsibleforaction;
       this.clodeadlinedate = clodeadlinedate;
    }
   
    public int getSalesactionplanid() {
        return this.salesactionplanid;
    }
    
    public void setSalesactionplanid(int salesactionplanid) {
        this.salesactionplanid = salesactionplanid;
    }
    public ClientMaster getClientMaster() {
        return this.clientMaster;
    }
    
    public void setClientMaster(ClientMaster clientMaster) {
        this.clientMaster = clientMaster;
    }
    public String getSpecificAction() {
        return this.specificAction;
    }
    
    public void setSpecificAction(String specificAction) {
        this.specificAction = specificAction;
    }
    public String getClocontactpersion() {
        return this.clocontactpersion;
    }
    
    public void setClocontactpersion(String clocontactpersion) {
        this.clocontactpersion = clocontactpersion;
    }
    public String getClopersonresponsibleforaction() {
        return this.clopersonresponsibleforaction;
    }
    
    public void setClopersonresponsibleforaction(String clopersonresponsibleforaction) {
        this.clopersonresponsibleforaction = clopersonresponsibleforaction;
    }
    public String getClodeadlinedate() {
        return this.clodeadlinedate;
    }
    
    public void setClodeadlinedate(String clodeadlinedate) {
        this.clodeadlinedate = clodeadlinedate;
    }




}


