package com.inm.ap.mode.hibernate;
// Generated Jan 31, 2018 3:59:00 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Salesactionplan generated by hbm2java
 */
public class Salesactionplan  implements java.io.Serializable {


     private int salesactionplanid;
     private ClientMaster clientMaster;
     private String specification;
     private String clocontactpersion;
     private String clopersonresponsibleforaction;
     private String clodatelinedate;

    public Salesactionplan() {
    }

	
    public Salesactionplan(int salesactionplanid, ClientMaster clientMaster) {
        this.salesactionplanid = salesactionplanid;
        this.clientMaster = clientMaster;
    }
    public Salesactionplan(int salesactionplanid, ClientMaster clientMaster, String specification, String clocontactpersion, String clopersonresponsibleforaction, String clodatelinedate) {
       this.salesactionplanid = salesactionplanid;
       this.clientMaster = clientMaster;
       this.specification = specification;
       this.clocontactpersion = clocontactpersion;
       this.clopersonresponsibleforaction = clopersonresponsibleforaction;
       this.clodatelinedate = clodatelinedate;
    }
   
    public int getSalesactionplanid() {
        return this.salesactionplanid;
    }
    
    public void setSalesactionplanid(int salesactionplanid) {
        this.salesactionplanid = salesactionplanid;
    }
    public ClientMaster getClientMaster() {
        return this.clientMaster;
    }
    
    public void setClientMaster(ClientMaster clientMaster) {
        this.clientMaster = clientMaster;
    }
    public String getSpecification() {
        return this.specification;
    }
    
    public void setSpecification(String specification) {
        this.specification = specification;
    }
    public String getClocontactpersion() {
        return this.clocontactpersion;
    }
    
    public void setClocontactpersion(String clocontactpersion) {
        this.clocontactpersion = clocontactpersion;
    }
    public String getClopersonresponsibleforaction() {
        return this.clopersonresponsibleforaction;
    }
    
    public void setClopersonresponsibleforaction(String clopersonresponsibleforaction) {
        this.clopersonresponsibleforaction = clopersonresponsibleforaction;
    }
    public String getClodatelinedate() {
        return this.clodatelinedate;
    }
    
    public void setClodatelinedate(String clodatelinedate) {
        this.clodatelinedate = clodatelinedate;
    }




}


