package com.inm.ap.mode.hibernate;
// Generated Feb 19, 2018 4:06:43 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * SignOff generated by hbm2java
 */
public class SignOff  implements java.io.Serializable {


     private int signoffid;
     private ClientMaster clientMaster;
     private String headofcorporatesignoff;
     private String rmsignoff;

    public SignOff() {
    }

	
    public SignOff(int signoffid, ClientMaster clientMaster) {
        this.signoffid = signoffid;
        this.clientMaster = clientMaster;
    }
    public SignOff(int signoffid, ClientMaster clientMaster, String headofcorporatesignoff, String rmsignoff) {
       this.signoffid = signoffid;
       this.clientMaster = clientMaster;
       this.headofcorporatesignoff = headofcorporatesignoff;
       this.rmsignoff = rmsignoff;
    }
   
    public int getSignoffid() {
        return this.signoffid;
    }
    
    public void setSignoffid(int signoffid) {
        this.signoffid = signoffid;
    }
    public ClientMaster getClientMaster() {
        return this.clientMaster;
    }
    
    public void setClientMaster(ClientMaster clientMaster) {
        this.clientMaster = clientMaster;
    }
    public String getHeadofcorporatesignoff() {
        return this.headofcorporatesignoff;
    }
    
    public void setHeadofcorporatesignoff(String headofcorporatesignoff) {
        this.headofcorporatesignoff = headofcorporatesignoff;
    }
    public String getRmsignoff() {
        return this.rmsignoff;
    }
    
    public void setRmsignoff(String rmsignoff) {
        this.rmsignoff = rmsignoff;
    }




}


