package com.inm.ap.mode.hibernate;
// Generated Feb 21, 2018 10:45:34 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * WalletResize generated by hbm2java
 */
public class WalletResize  implements java.io.Serializable {


     private int walletResizeId;
     private Lookupmaster lookupmasterByProduct;
     private Lookupmaster lookupmasterByCurrencyLookupid;
     private ClientMaster clientMaster;
     private BigDecimal interestRate;
     private BigDecimal ftpRate;
     private BigDecimal processingFees;
     private BigDecimal tenor;
     private BigDecimal margin;
     private BigDecimal disbursedAmount;
     private BigDecimal limit;
     private BigDecimal averageUtilizationAmount;
     private BigDecimal annualAverageFloat;
     private BigDecimal totalrevenue;
     private BigDecimal percentagePerAnnum;
     private BigDecimal percentageFlatFee;
     private BigDecimal drawdownAmount;
     private BigDecimal amountDeposited;
     private BigDecimal timesRolledOverInAYrear;
     private BigDecimal numberOfQuarters;
     private BigDecimal percentageAllInclusive;
     private BigDecimal percentagePerQuarter;
     private BigDecimal flatFeeAmount;
     private BigDecimal quarterlyOpeningCommRate;
     private BigDecimal acceptanceCommissionRate;
     private BigDecimal retirementCommissionRate;
     private BigDecimal tariff;
     private BigDecimal handlingCommissionRate;
     private BigDecimal discountedAmount;
     private BigDecimal spread;
     private BigDecimal annualPremiumAmount;
     private String insuranceCompany;
     private BigDecimal discountingRate;

    public WalletResize() {
    }

	
    public WalletResize(int walletResizeId, Lookupmaster lookupmasterByCurrencyLookupid, ClientMaster clientMaster) {
        this.walletResizeId = walletResizeId;
        this.lookupmasterByCurrencyLookupid = lookupmasterByCurrencyLookupid;
        this.clientMaster = clientMaster;
    }
    public WalletResize(int walletResizeId, Lookupmaster lookupmasterByProduct, Lookupmaster lookupmasterByCurrencyLookupid, ClientMaster clientMaster, BigDecimal interestRate, BigDecimal ftpRate, BigDecimal processingFees, BigDecimal tenor, BigDecimal margin, BigDecimal disbursedAmount, BigDecimal limit, BigDecimal averageUtilizationAmount, BigDecimal annualAverageFloat, BigDecimal totalrevenue, BigDecimal percentagePerAnnum, BigDecimal percentageFlatFee, BigDecimal drawdownAmount, BigDecimal amountDeposited, BigDecimal timesRolledOverInAYrear, BigDecimal numberOfQuarters, BigDecimal percentageAllInclusive, BigDecimal percentagePerQuarter, BigDecimal flatFeeAmount, BigDecimal quarterlyOpeningCommRate, BigDecimal acceptanceCommissionRate, BigDecimal retirementCommissionRate, BigDecimal tariff, BigDecimal handlingCommissionRate, BigDecimal discountedAmount, BigDecimal spread, BigDecimal annualPremiumAmount, String insuranceCompany, BigDecimal discountingRate) {
       this.walletResizeId = walletResizeId;
       this.lookupmasterByProduct = lookupmasterByProduct;
       this.lookupmasterByCurrencyLookupid = lookupmasterByCurrencyLookupid;
       this.clientMaster = clientMaster;
       this.interestRate = interestRate;
       this.ftpRate = ftpRate;
       this.processingFees = processingFees;
       this.tenor = tenor;
       this.margin = margin;
       this.disbursedAmount = disbursedAmount;
       this.limit = limit;
       this.averageUtilizationAmount = averageUtilizationAmount;
       this.annualAverageFloat = annualAverageFloat;
       this.totalrevenue = totalrevenue;
       this.percentagePerAnnum = percentagePerAnnum;
       this.percentageFlatFee = percentageFlatFee;
       this.drawdownAmount = drawdownAmount;
       this.amountDeposited = amountDeposited;
       this.timesRolledOverInAYrear = timesRolledOverInAYrear;
       this.numberOfQuarters = numberOfQuarters;
       this.percentageAllInclusive = percentageAllInclusive;
       this.percentagePerQuarter = percentagePerQuarter;
       this.flatFeeAmount = flatFeeAmount;
       this.quarterlyOpeningCommRate = quarterlyOpeningCommRate;
       this.acceptanceCommissionRate = acceptanceCommissionRate;
       this.retirementCommissionRate = retirementCommissionRate;
       this.tariff = tariff;
       this.handlingCommissionRate = handlingCommissionRate;
       this.discountedAmount = discountedAmount;
       this.spread = spread;
       this.annualPremiumAmount = annualPremiumAmount;
       this.insuranceCompany = insuranceCompany;
       this.discountingRate = discountingRate;
    }
   
    public int getWalletResizeId() {
        return this.walletResizeId;
    }
    
    public void setWalletResizeId(int walletResizeId) {
        this.walletResizeId = walletResizeId;
    }
    public Lookupmaster getLookupmasterByProduct() {
        return this.lookupmasterByProduct;
    }
    
    public void setLookupmasterByProduct(Lookupmaster lookupmasterByProduct) {
        this.lookupmasterByProduct = lookupmasterByProduct;
    }
    public Lookupmaster getLookupmasterByCurrencyLookupid() {
        return this.lookupmasterByCurrencyLookupid;
    }
    
    public void setLookupmasterByCurrencyLookupid(Lookupmaster lookupmasterByCurrencyLookupid) {
        this.lookupmasterByCurrencyLookupid = lookupmasterByCurrencyLookupid;
    }
    public ClientMaster getClientMaster() {
        return this.clientMaster;
    }
    
    public void setClientMaster(ClientMaster clientMaster) {
        this.clientMaster = clientMaster;
    }
    public BigDecimal getInterestRate() {
        return this.interestRate;
    }
    
    public void setInterestRate(BigDecimal interestRate) {
        this.interestRate = interestRate;
    }
    public BigDecimal getFtpRate() {
        return this.ftpRate;
    }
    
    public void setFtpRate(BigDecimal ftpRate) {
        this.ftpRate = ftpRate;
    }
    public BigDecimal getProcessingFees() {
        return this.processingFees;
    }
    
    public void setProcessingFees(BigDecimal processingFees) {
        this.processingFees = processingFees;
    }
    public BigDecimal getTenor() {
        return this.tenor;
    }
    
    public void setTenor(BigDecimal tenor) {
        this.tenor = tenor;
    }
    public BigDecimal getMargin() {
        return this.margin;
    }
    
    public void setMargin(BigDecimal margin) {
        this.margin = margin;
    }
    public BigDecimal getDisbursedAmount() {
        return this.disbursedAmount;
    }
    
    public void setDisbursedAmount(BigDecimal disbursedAmount) {
        this.disbursedAmount = disbursedAmount;
    }
    public BigDecimal getLimit() {
        return this.limit;
    }
    
    public void setLimit(BigDecimal limit) {
        this.limit = limit;
    }
    public BigDecimal getAverageUtilizationAmount() {
        return this.averageUtilizationAmount;
    }
    
    public void setAverageUtilizationAmount(BigDecimal averageUtilizationAmount) {
        this.averageUtilizationAmount = averageUtilizationAmount;
    }
    public BigDecimal getAnnualAverageFloat() {
        return this.annualAverageFloat;
    }
    
    public void setAnnualAverageFloat(BigDecimal annualAverageFloat) {
        this.annualAverageFloat = annualAverageFloat;
    }
    public BigDecimal getTotalrevenue() {
        return this.totalrevenue;
    }
    
    public void setTotalrevenue(BigDecimal totalrevenue) {
        this.totalrevenue = totalrevenue;
    }
    public BigDecimal getPercentagePerAnnum() {
        return this.percentagePerAnnum;
    }
    
    public void setPercentagePerAnnum(BigDecimal percentagePerAnnum) {
        this.percentagePerAnnum = percentagePerAnnum;
    }
    public BigDecimal getPercentageFlatFee() {
        return this.percentageFlatFee;
    }
    
    public void setPercentageFlatFee(BigDecimal percentageFlatFee) {
        this.percentageFlatFee = percentageFlatFee;
    }
    public BigDecimal getDrawdownAmount() {
        return this.drawdownAmount;
    }
    
    public void setDrawdownAmount(BigDecimal drawdownAmount) {
        this.drawdownAmount = drawdownAmount;
    }
    public BigDecimal getAmountDeposited() {
        return this.amountDeposited;
    }
    
    public void setAmountDeposited(BigDecimal amountDeposited) {
        this.amountDeposited = amountDeposited;
    }
    public BigDecimal getTimesRolledOverInAYrear() {
        return this.timesRolledOverInAYrear;
    }
    
    public void setTimesRolledOverInAYrear(BigDecimal timesRolledOverInAYrear) {
        this.timesRolledOverInAYrear = timesRolledOverInAYrear;
    }
    public BigDecimal getNumberOfQuarters() {
        return this.numberOfQuarters;
    }
    
    public void setNumberOfQuarters(BigDecimal numberOfQuarters) {
        this.numberOfQuarters = numberOfQuarters;
    }
    public BigDecimal getPercentageAllInclusive() {
        return this.percentageAllInclusive;
    }
    
    public void setPercentageAllInclusive(BigDecimal percentageAllInclusive) {
        this.percentageAllInclusive = percentageAllInclusive;
    }
    public BigDecimal getPercentagePerQuarter() {
        return this.percentagePerQuarter;
    }
    
    public void setPercentagePerQuarter(BigDecimal percentagePerQuarter) {
        this.percentagePerQuarter = percentagePerQuarter;
    }
    public BigDecimal getFlatFeeAmount() {
        return this.flatFeeAmount;
    }
    
    public void setFlatFeeAmount(BigDecimal flatFeeAmount) {
        this.flatFeeAmount = flatFeeAmount;
    }
    public BigDecimal getQuarterlyOpeningCommRate() {
        return this.quarterlyOpeningCommRate;
    }
    
    public void setQuarterlyOpeningCommRate(BigDecimal quarterlyOpeningCommRate) {
        this.quarterlyOpeningCommRate = quarterlyOpeningCommRate;
    }
    public BigDecimal getAcceptanceCommissionRate() {
        return this.acceptanceCommissionRate;
    }
    
    public void setAcceptanceCommissionRate(BigDecimal acceptanceCommissionRate) {
        this.acceptanceCommissionRate = acceptanceCommissionRate;
    }
    public BigDecimal getRetirementCommissionRate() {
        return this.retirementCommissionRate;
    }
    
    public void setRetirementCommissionRate(BigDecimal retirementCommissionRate) {
        this.retirementCommissionRate = retirementCommissionRate;
    }
    public BigDecimal getTariff() {
        return this.tariff;
    }
    
    public void setTariff(BigDecimal tariff) {
        this.tariff = tariff;
    }
    public BigDecimal getHandlingCommissionRate() {
        return this.handlingCommissionRate;
    }
    
    public void setHandlingCommissionRate(BigDecimal handlingCommissionRate) {
        this.handlingCommissionRate = handlingCommissionRate;
    }
    public BigDecimal getDiscountedAmount() {
        return this.discountedAmount;
    }
    
    public void setDiscountedAmount(BigDecimal discountedAmount) {
        this.discountedAmount = discountedAmount;
    }
    public BigDecimal getSpread() {
        return this.spread;
    }
    
    public void setSpread(BigDecimal spread) {
        this.spread = spread;
    }
    public BigDecimal getAnnualPremiumAmount() {
        return this.annualPremiumAmount;
    }
    
    public void setAnnualPremiumAmount(BigDecimal annualPremiumAmount) {
        this.annualPremiumAmount = annualPremiumAmount;
    }
    public String getInsuranceCompany() {
        return this.insuranceCompany;
    }
    
    public void setInsuranceCompany(String insuranceCompany) {
        this.insuranceCompany = insuranceCompany;
    }
    public BigDecimal getDiscountingRate() {
        return this.discountingRate;
    }
    
    public void setDiscountingRate(BigDecimal discountingRate) {
        this.discountingRate = discountingRate;
    }




}


